"""create rooms table

Revision ID: 903c82a891c0
Revises: fe0f9cbd9f66
Create Date: 2026-06-08 03:48:01.603031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '903c82a891c0'
down_revision: Union[str, Sequence[str], None] = 'fe0f9cbd9f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'check_in',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('bookings', 'check_out',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.alter_column('bookings', 'check_out',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('bookings', 'check_in',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
