"""sync models

Revision ID: cd9fb90b37b6
Revises: a0252093efc1
Create Date: 2026-06-08 02:35:33.700886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd9fb90b37b6'
down_revision: Union[str, Sequence[str], None] = 'a0252093efc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'check_out')
    op.drop_column('bookings', 'check_in')
    op.alter_column('guests', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guests', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guests', 'room_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_rooms_room_number'), table_name='rooms')
    op.drop_column('rooms', 'price')
    op.drop_column('rooms', 'is_available')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('rooms', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_rooms_room_number'), 'rooms', ['room_number'], unique=True)
    op.alter_column('guests', 'room_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('guests', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guests', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('bookings', sa.Column('check_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('check_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
