"""add room price and availability

Revision ID: e583988d73cc
Revises: 903c82a891c0
Create Date: 2026-06-10 15:24:48.408657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e583988d73cc'
down_revision: Union[str, Sequence[str], None] = '903c82a891c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'is_available')
    op.drop_column('rooms', 'price')
    # ### end Alembic commands ###
