"""add booking dates

Revision ID: fe0f9cbd9f66
Revises: 1a61887bfbf7
Create Date: 2026-06-08 03:18:39.968447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0f9cbd9f66'
down_revision: Union[str, Sequence[str], None] = '1a61887bfbf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('check_in', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('check_out', sa.Date(), nullable=False))
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_column('bookings', 'check_out')
    op.drop_column('bookings', 'check_in')
    # ### end Alembic commands ###
